class SurahData {
  static const List<SurahInfo> list = [
    SurahInfo(1, 'Al-Fatihah', 'الفاتحة'),
    SurahInfo(2, 'Al-Baqarah', 'البقرة'),
    SurahInfo(3, 'Ali Imran', 'آل عمران'),
    SurahInfo(4, 'An-Nisa', 'النساء'),
    SurahInfo(5, 'Al-Ma’idah', 'المائدة'),
    SurahInfo(6, 'Al-An’am', 'الأنعام'),
    SurahInfo(7, 'Al-A’raf', 'الأعراف'),
    SurahInfo(8, 'Al-Anfal', 'الأنفال'),
    SurahInfo(9, 'At-Taubah', 'التوبة'),
    SurahInfo(10, 'Yunus', 'يونس'),
    SurahInfo(11, 'Hud', 'هود'),
    SurahInfo(12, 'Yusuf', 'يوسف'),
    SurahInfo(13, 'Ar-Ra’d', 'الرعد'),
    SurahInfo(14, 'Ibrahim', 'إبراهيم'),
    SurahInfo(15, 'Al-Hijr', 'الحجر'),
    SurahInfo(16, 'An-Nahl', 'النحل'),
    SurahInfo(17, 'Al-Isra', 'الإسراء'),
    SurahInfo(18, 'Al-Kahf', 'الكهف'),
    SurahInfo(19, 'Maryam', 'مريم'),
    SurahInfo(20, 'Ta-Ha', 'طه'),
    SurahInfo(21, 'Al-Anbiya', 'الأنبياء'),
    SurahInfo(22, 'Al-Hajj', 'الحج'),
    SurahInfo(23, 'Al-Mu’minun', 'المؤمنون'),
    SurahInfo(24, 'An-Nur', 'النور'),
    SurahInfo(25, 'Al-Furqan', 'الفرقان'),
    SurahInfo(26, 'Asy-Syu’ara', 'الشعراء'),
    SurahInfo(27, 'An-Naml', 'النمل'),
    SurahInfo(28, 'Al-Qasas', 'القصص'),
    SurahInfo(29, 'Al-Ankabut', 'العنكبوت'),
    SurahInfo(30, 'Ar-Rum', 'الروم'),
    SurahInfo(31, 'Luqman', 'لقمان'),
    SurahInfo(32, 'As-Sajdah', 'السجدة'),
    SurahInfo(33, 'Al-Ahzab', 'الأحزاب'),
    SurahInfo(34, 'Saba’', 'سبأ'),
    SurahInfo(35, 'Fatir', 'فاطر'),
    SurahInfo(36, 'Ya-Sin', 'يس'),
    SurahInfo(37, 'As-Saffat', 'الصافات'),
    SurahInfo(38, 'Sad', 'ص'),
    SurahInfo(39, 'Az-Zumar', 'الزمر'),
    SurahInfo(40, 'Ghafir', 'غافر'),
    SurahInfo(41, 'Fussilat', 'فصلت'),
    SurahInfo(42, 'Asy-Syura', 'الشورى'),
    SurahInfo(43, 'Az-Zukhruf', 'الزخرف'),
    SurahInfo(44, 'Ad-Dukhan', 'الدخان'),
    SurahInfo(45, 'Al-Jasiyah', 'الجاثية'),
    SurahInfo(46, 'Al-Ahqaf', 'الأحقاف'),
    SurahInfo(47, 'Muhammad', 'محمد'),
    SurahInfo(48, 'Al-Fath', 'الفتح'),
    SurahInfo(49, 'Al-Hujurat', 'الحجرات'),
    SurahInfo(50, 'Qaf', 'ق'),
    SurahInfo(51, 'Az-Zariyat', 'الذاريات'),
    SurahInfo(52, 'At-Tur', 'الطور'),
    SurahInfo(53, 'An-Najm', 'النجم'),
    SurahInfo(54, 'Al-Qamar', 'القمر'),
    SurahInfo(55, 'Ar-Rahman', 'الرحمن'),
    SurahInfo(56, 'Al-Waqi’ah', 'الواقعة'),
    SurahInfo(57, 'Al-Hadid', 'الحديد'),
    SurahInfo(58, 'Al-Mujadilah', 'المجادلة'),
    SurahInfo(59, 'Al-Hasyr', 'الحشر'),
    SurahInfo(60, 'Al-Mumtahanah', 'الممتحنة'),
    SurahInfo(61, 'As-Saff', 'الصف'),
    SurahInfo(62, 'Al-Jumu’ah', 'الجمعة'),
    SurahInfo(63, 'Al-Munafiqun', 'المنافقون'),
    SurahInfo(64, 'At-Taghabun', 'التغابن'),
    SurahInfo(65, 'At-Talaq', 'الطلاق'),
    SurahInfo(66, 'At-Tahrim', 'التحريم'),
    SurahInfo(67, 'Al-Mulk', 'الملك'),
    SurahInfo(68, 'Al-Qalam', 'القلم'),
    SurahInfo(69, 'Al-Haqqah', 'الحاقة'),
    SurahInfo(70, 'Al-Ma’arij', 'المعارج'),
    SurahInfo(71, 'Nuh', 'نوح'),
    SurahInfo(72, 'Al-Jinn', 'الجن'),
    SurahInfo(73, 'Al-Muzzammil', 'المزمل'),
    SurahInfo(74, 'Al-Muddassir', 'المدثر'),
    SurahInfo(75, 'Al-Qiyamah', 'القيامة'),
    SurahInfo(76, 'Al-Insan', 'الإنسان'),
    SurahInfo(77, 'Al-Mursalat', 'المرسلات'),
    SurahInfo(78, 'An-Naba', 'النبأ'),
    SurahInfo(79, 'An-Nazi’at', 'النازعات'),
    SurahInfo(80, 'Abasa', 'عبس'),
    SurahInfo(81, 'At-Takwir', 'التكوير'),
    SurahInfo(82, 'Al-Infitar', 'الإنفطار'),
    SurahInfo(83, 'Al-Mutaffifin', 'المطففين'),
    SurahInfo(84, 'Al-Insyiqaq', 'الإنشقاق'),
    SurahInfo(85, 'Al-Buruj', 'البروج'),
    SurahInfo(86, 'At-Tariq', 'الطارق'),
    SurahInfo(87, 'Al-A’la', 'الأعلى'),
    SurahInfo(88, 'Al-Ghasyiyah', 'الغاشية'),
    SurahInfo(89, 'Al-Fajr', 'الفجر'),
    SurahInfo(90, 'Al-Balad', 'البلد'),
    SurahInfo(91, 'Asy-Syams', 'الشمس'),
    SurahInfo(92, 'Al-Lail', 'الليل'),
    SurahInfo(93, 'Ad-Duha', 'الضحى'),
    SurahInfo(94, 'Asy-Syarh', 'الشرح'),
    SurahInfo(95, 'At-Tin', 'التين'),
    SurahInfo(96, 'Al-‘Alaq', 'العلق'),
    SurahInfo(97, 'Al-Qadr', 'القدر'),
    SurahInfo(98, 'Al-Bayyinah', 'البينة'),
    SurahInfo(99, 'Az-Zalzalah', 'الزلزلة'),
    SurahInfo(100, 'Al-‘Adiyat', 'العاديات'),
    SurahInfo(101, 'Al-Qari’ah', 'القارعة'),
    SurahInfo(102, 'At-Takatsur', 'التكاثر'),
    SurahInfo(103, 'Al-‘Asr', 'العصر'),
    SurahInfo(104, 'Al-Humazah', 'الهمزة'),
    SurahInfo(105, 'Al-Fil', 'الفيل'),
    SurahInfo(106, 'Quraisy', 'قريش'),
    SurahInfo(107, 'Al-Ma’un', 'الماعون'),
    SurahInfo(108, 'Al-Kautsar', 'الكوثر'),
    SurahInfo(109, 'Al-Kafirun', 'الكافرون'),
    SurahInfo(110, 'An-Nasr', 'النصر'),
    SurahInfo(111, 'Al-Lahab', 'المسد'),
    SurahInfo(112, 'Al-Ikhlas', 'الإخلاص'),
    SurahInfo(113, 'Al-Falaq', 'الفلق'),
    SurahInfo(114, 'An-Nas', 'الناس'),
  ];

  static SurahInfo byNumber(int number) {
    return list.firstWhere((s) => s.number == number);
  }
}

class SurahInfo {
  final int number;
  final String latin;
  final String arabic;

  const SurahInfo(this.number, this.latin, this.arabic);
}


